# Generated by Django 4.1.7 on 2023-03-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.PositiveIntegerField(unique=True)),
                ('indexed_block', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveIntegerField(unique=True)),
                ('owner', models.CharField(max_length=255, verbose_name='Owners')),
                ('image', models.FileField(upload_to='images/')),
                ('chain_id', models.PositiveIntegerField()),
                ('tx', models.CharField(max_length=255)),
                ('block_number', models.PositiveBigIntegerField()),
                ('skill', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('blockchain_timestamp', models.PositiveBigIntegerField(default=None, null=True)),
                ('ipfs_uri_image', models.CharField(max_length=100, verbose_name='ifps uri image')),
            ],
        ),
    ]
