# Generated by Django 4.1.7 on 2023-03-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='ipfs_uri_image',
        ),
        migrations.AddField(
            model_name='token',
            name='token_url',
            field=models.CharField(default='http://', max_length=512),
            preserve_default=False,
        ),
    ]
