# Generated by Django 4.1.7 on 2023-03-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacta', '0003_action_action_non_empty_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='json_metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='polybase_token_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
