# Generated by Django 4.1.7 on 2023-03-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacta', '0004_token_json_metadata_token_polybase_token_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='image',
        ),
    ]
