# Generated by Django 4.1.7 on 2023-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacta', '0005_remove_token_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='image',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
